language: node_js
node_js:
- '8'
script:
- npm run test
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep-history: true
    localdir: .site
    on:
      branch: master