language: node_js
node_js:
  - '8'
before_script:
  - yarn bootstrap
script:
  - npm run travis-test
  - yarn build
  - ./bin/travis-prep-website.sh
  - 'if [ "${TRAVIS_BRANCH}" == "develop" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then yarn snapshots; else echo "snapshots are only enabled on the develop branch"; fi'
cache:
  yarn: true
  directories:
    - .npm
    - node_modules
    - packages/style/website/node_modules
    - packages/style/node_modules
    - packages/portal-style/website/node_modules
    - packages/portal-style/node_modules
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep-history: true
    local-dir: target/portal-components
    on:
      branch: develop
  - provider: npm
    email: julien.ducro@deskpro.com
    api_key:
      secure: iGNdyMSvrHeG0JIG/imjIVcLyBcCzUp/+zYZBUbcadjAyStXrboHfkvXE4nRwan8tocnfDiOfsgAacp+g+UILzHkcfMD0EzWufa16EHwLIXZyDb+poK7oQ2FL3AvcS7X/CWfWeHGEOQ9/6uIta3Wk8dIPPm178yOzWkaV104itcT1b+xM8JQlMEIEXe0CP2B4OasP/bztH0n6+Q5MoUk4GsOFQK3Eb+tTj0f6QRNmClAzmV8m8j65KmGYKEG6PhJGIAR54KDWCbtCKNuNjkKq8gajg8naeYCeuTHKBsq4oB3kUI18jAIgLUb54WM935Lx3mMR5sZdmjzHMCh59iJVDUu8t2kpv6XhCI7sCynY/3tXMIUvWC0g+uqA5kzAdsvOs/CMM2H0RdEppdlRHKbVntos6ETtZA29RlfW64Z4s+IrzZCoeZROOb3jveDyJaqU5bDRydDkfkrQgz+Nm/15CWOK6mBKzCf6ON0o83NaZ1EpjP9DtshBLa5BfJjuk3fq/Z4JTTGHFrxKMbhW9mbDaqQP4cRBzo1bE04sTt4upPierpg6WknhEIsiwo/44UbadYKitMJLGq+pQDhpDNhGz3CPdm3bNbWNoaG1P81me48igOIcbvaCXH1q8OhJlidmrfoONtMtaMek76NY/vuWeJxWGK+bIun76aLqZd8Hx4=
    on:
      branch: master
      tags: true
      repo: deskpro/portal-components
