language: node_js
dist: focal
node_js:
  - '18'
before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/components/.npmrc
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/portal-style/.npmrc

before_script:
  - yarn
script:
  - yarn test
  - yarn build
  - yarn build-storybook
  - ./bin/travis-prep-website.sh
cache:
  directories:
    - .npm
    - node_modules
    - packages/portal-style/website/node_modules
    - packages/portal-style/node_modules
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep-history: true
    local-dir: target/portal-components
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: npm run publish-npm -- $(node bin/lerna-version.js)
    on:
      tags: true
      branch: develop
