language: node_js
node_js:
  - '8'
before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/components/.npmrc
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/portal-style/.npmrc

before_script:
  - npm install -g lerna gulp
  - lerna bootstrap
script:
  # TEMP disabled because coveralls is down
  #- npm run travis-test
  - npm run build
  - ./bin/travis-prep-website.sh
#  - 'if [ "${TRAVIS_BRANCH}" == "develop" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then npm run snapshots; else echo "snapshots are only enabled on the develop branch"; fi'
cache:
  directories:
    - .npm
    - node_modules
    - packages/style/website/node_modules
    - packages/style/node_modules
    - packages/portal-style/website/node_modules
    - packages/portal-style/node_modules
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep-history: true
    local-dir: target/portal-components
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: npm run publish-npm -- $(node bin/lerna-version.js)
    on:
      tags: true
